# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Enable mouse
set -g mouse on

# Enable OSC 52 for clipboard passthrough
set -g set-clipboard on
set -g allow-passthrough on

# Start window and pane numbering at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Color config
set-option -sa terminal-overrides ",xterm*:Tc"

# Status
set-option -g status-position top
set-option -g status-style bg=default
set -g status-justify absolute-centre
set -g status-left-length 30
set -g status-left '#[fg=gray]#{user}@#H'
set -g status-right '#[fg=gray][#S]'
set -g window-status-separator ' #[fg=gray]· '
set -g window-status-format "#[fg=blue]#W#[fg=default]"
set -g window-status-current-format "#[fg=magenta,bold][#W]#[fg=default]"
set -g message-style "fg=magenta,bg=default"
set -g message-command-style "fg=magenta,bg=default"

# Split and open window in cwd
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
